### ISSUE TITLE
Docgen for 6.8 plugins isn't producing output

### ISSUE THREAD

**Issue by karenzone** [elastic/docs-tools#36]
Jenkins Ondemand jobs failing for 6.8: Build number `#32` and `#40` (Is it OK to link to jobs here?)
Manual docgen failing on `rake test:install-core`:
```
Karens-MBP:logstash karenmetts$ rake test:install-core
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.ext.openssl.SecurityHelper (file:/Users/karenmetts/src/github/elastic/logstash/vendor/jruby/lib/ruby/stdlib/jopenssl.jar) to constructor java.security.cert.CertificateFactory(java.security.cert.CertificateFactorySpi,java.security.Provider,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jruby.ext.openssl.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Invoking bundler install...
Plugin version conflict, aborting
rake aborted!
Bundler::VersionConflict: Bundler could not find compatible versions for gem "gems":
  In snapshot (Gemfile.lock):
    gems (= 1.2.0)

  In Gemfile:
    gems (~> 1) java

    logstash-core java was resolved to 6.8.5, which depends on
      gems (~> 0.8.3) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/resolver.rb:56:in `start'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/resolver.rb:22:in `resolve'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:258:in `resolve'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:158:in `resolve_remotely!'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/installer.rb:310:in `resolve_if_needed'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/installer.rb:84:in `block in run'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/process_lock.rb:12:in `block in lock'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/process_lock.rb:9:in `lock'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/installer.rb:73:in `run'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/installer.rb:25:in `install'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/install.rb:65:in `run'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:235:in `block in install'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/settings.rb:143:in `temporary'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:234:in `install'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:160:in `execute_bundler'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:131:in `block in execute_bundler_with_retry'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:129:in `block in execute_bundler_with_retry'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:203:in `capture_stdout'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:128:in `execute_bundler_with_retry'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:118:in `invoke!'
/Users/karenmetts/src/github/elastic/logstash/rakelib/vendor.rake:21:in `block in <main>'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<main>'

Caused by:
Bundler::Molinillo::VersionConflict: Unable to satisfy the following requirements:

- `gems (~> 1) java` required by `Gemfile`
- `gems (= 1.2.0)` required by `Gemfile.lock`
- `gems (~> 0.8.3) java` required by `logstash-core (6.8.5)`
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:257:in `process_topmost_state'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:39:in `resolve'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/resolver.rb:50:in `start'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/resolver.rb:22:in `resolve'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:258:in `resolve'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/definition.rb:158:in `resolve_remotely!'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/installer.rb:310:in `resolve_if_needed'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/installer.rb:84:in `block in run'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/process_lock.rb:12:in `block in lock'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/process_lock.rb:9:in `lock'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/installer.rb:73:in `run'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/installer.rb:25:in `install'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli/install.rb:65:in `run'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:235:in `block in install'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/settings.rb:143:in `temporary'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:234:in `install'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:160:in `execute_bundler'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:131:in `block in execute_bundler_with_retry'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:129:in `block in execute_bundler_with_retry'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:203:in `capture_stdout'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:128:in `execute_bundler_with_retry'
/Users/karenmetts/src/github/elastic/logstash/lib/bootstrap/bundler.rb:118:in `invoke!'
/Users/karenmetts/src/github/elastic/logstash/rakelib/vendor.rake:21:in `block in <main>'
/Users/karenmetts/src/github/elastic/logstash/vendor/bundle/jruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<main>'
Tasks: TOP => test:install-core => bootstrap => vendor:all => vendor:gems
(See full trace by running task with --trace)
```

**Comment by karenzone** [comment]
@jsvd. Thank you for the collection of fixes (including https://github.com/elastic/logstash/pull/11649) that you made to get the 6.8 branch building again.
<3
